### PR TITLE
Add english version of coconut cookies

### PR DESCRIPTION
**Pull request by jan-warchol**
Things I'm not sure about:
* [x] what's correct english name for `kleik ryżowy`?
* [x] is `air circulation` correct name for the thing that some ovens have (fan mixing the air inside)?

### CODE REVIEW

**Comment by juanitobailey** [comment]
kleik ryżowy -> rice porridge
Fan assisted ovens

**Comment by SAllen-1** [comment]
Rice gruel = rice flour??

**Comment by jan-warchol** [comment]
Thanks @juanitobailey ! @SAllen-1 No, it's not flour, it's something else - usually small children eat this (mixed with water).

By the way, I just spotted one more thing: is `coconut flakes` the correct translation for `wiórki kokosowe`? Or should it rather be `shredded coconut`?

**Comment by jan-warchol** [comment]
> By the way, I've just spotted one more thing: is `coconut flakes` the correct translation for `wiórki kokosowe`? Or should it rather be `shredded coconut`?

Okay, judging by google image search results, shredded coconut seems more appropriate.

**Pull request merged**
